## Etapa 1

In [1]:
# Importação das bibliotecas necessárias e carregamento do dataset
import pandas as pd
from IPython.display import display

dados_ibovespa = pd.read_csv('dados_historicos_ibovespa.csv')

## Etapa 2

In [2]:
# Inspeção do dataset
print("Dados Iníciais do DataFrame:")
display(dados_ibovespa.head(20)) # As Colunas Data, Vol. e Var% são str deveriam ser object

print("Dados Finais do DataFrame:")
display(dados_ibovespa.tail(20)) # As Colunas Data, Vol. e Var% são str deveriam ser object

print("Quandidade de linhas e colunas:")
print(f"Linhas: {dados_ibovespa.shape[0]}")
print(f"Colunas: {dados_ibovespa.shape[1]}")

Dados Iníciais do DataFrame:

          Data   Último  Abertura   Máxima   Mínima    Vol.    Var%
0   05.06.2024  121.407   121.803  122.170  121.253   8,77M  -0,32%
1   04.06.2024  121.802   122.032  122.032  120.878   8,53M  -0,19%
2   03.06.2024  122.032   122.100  122.495  121.496   8,43M  -0,05%
3   31.05.2024  122.098   122.704  122.837  121.929  15,92M  -0,50%
4   29.05.2024  122.707   123.780  123.780  122.458   8,26M  -0,87%
5   28.05.2024  123.780   124.498  125.392  123.537   9,18M  -0,58%
6   27.05.2024  124.496   124.297  124.535  124.081   4,33M   0,15%
7   24.05.2024  124.306   124.731  125.257  124.259   9,21M  -0,34%
8   23.05.2024  124.729   125.650  125.665  124.431   9,99M  -0,73%
9   22.05.2024  125.650   127.412  127.412  125.524  12,40M  -1,38%
10  21.05.2024  127.412   127.754  128.272  127.205   9,14M  -0,27%
11  20.05.2024  127.751   128.151  128.730  127.488   9,34M  -0,31%
12  17.05.2024  128.151   128.280  128.464  127.696  10,26M  -0,10%
13  16.05.2024  128.284   128.029  128.965  127.922   9,86M   0,20%
14  15.05.2024  128.028   128.514  128.646  127.029  10,86M  -0,38%
15  14.05.2024  128.515   128.155  128.965  127.962  11,89M   0,28%
16  13.05.2024  128.155   127.600  128.669  127.599   8,92M   0,44%
17  10.05.2024  127.600   128.188  129.022  127.467  12,57M  -0,46%
18  09.05.2024  128.188   129.468  129.468  127.376  13,37M  -1,00%
19  08.05.2024  129.481   129.210  129.564  128.048   9,79M   0,21%

Dados Finais do DataFrame:

           Data  Último  Abertura  Máxima  Mínima    Vol.    Var%
975  03.07.2020  96.765    96.237  96.765  95.803   5,35M   0,55%
976  02.07.2020  96.235    96.206  97.864  96.052  10,06M   0,03%
977  01.07.2020  96.203    95.062  96.852  95.062  10,16M   1,21%
978  30.06.2020  95.056    95.728  96.257  94.806  10,14M  -0,71%
979  29.06.2020  95.735    93.837  95.735  93.825   8,91M   2,03%
980  26.06.2020  93.834    95.979  95.979  93.514   8,44M  -2,24%
981  25.06.2020  95.983    94.382  96.260  94.152   8,70M   1,70%
982  24.06.2020  94.377    95.974  95.974  93.259   9,96M  -1,67%
983  23.06.2020  95.975    95.344  97.486  95.344   9,75M   0,67%
984  22.06.2020  95.336    96.572  96.870  94.869   8,26M  -1,28%
985  19.06.2020  96.572    96.138  97.540  95.874  13,13M   0,47%
986  18.06.2020  96.125    95.547  97.110  94.698  10,01M   0,60%
987  17.06.2020  95.547    93.531  96.611  93.531  11,13M   2,16%
988  16.06.2020  93.531    92.387  95.216  92.387  12,03M   1,25%
989  15.06.2020  92.376    92.780  93.112  90.148  13,32M  -0,45%
990  12.06.2020  92.795    94.677  94.703  90.811  12,79M  -2,00%
991  10.06.2020  94.686    96.747  97.646  94.665  11,74M  -2,13%
992  09.06.2020  96.747    97.644  97.644  95.386  11,29M  -0,92%
993  08.06.2020  97.645    94.640  97.693  94.635  11,10M   3,18%
994  05.06.2020  94.637    93.839  97.356  93.839  13,32M   0,86%

Quandidade de linhas e colunas:
Linhas: 995
Colunas: 7

## Etapa 3

In [3]:
# Tipos dos dados
print("Informações gerais do DataFrame:")
display(dados_ibovespa.info())

Informações gerais do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      995 non-null    str
 1   Último    995 non-null    float64
 2   Abertura  995 non-null    float64
 3   Máxima    995 non-null    float64
 4   Mínima    995 non-null    float64
 5   Vol.      995 non-null    str
 6   Var%      995 non-null    str
dtypes: float64(4), str(3)
memory usage: 54.5 KB

None

Ponto de atenção

O `Dtype` das colunas `Data`, `Vol.` e `Var%` estão com tipo `str`, mas deveriam ser `object`

## Etapa 4

In [4]:
# Estatística descritiva

print("Descrição estatística do DataFrame:")
display(dados_ibovespa.describe())

Descrição estatística do DataFrame:

           Último    Abertura      Máxima      Mínima
count  995.000000  995.000000  995.000000  995.000000
mean   113.460895  113.433682  114.409564  112.481545
std      9.556273    9.572786    9.439067    9.646551
min     92.376000   92.387000   93.112000   90.148000
25%    106.080500  106.039000  106.993000  105.040500
50%    113.262000  113.228000  114.213000  112.135000
75%    119.889500  119.798000  120.816500  118.961000
max    134.194000  134.194000  134.392000  133.832000

## Etapa 5

In [5]:
# Missing values

print("Valores ausentes: \n")
missing = dados_ibovespa.isnull().sum()
display(missing)

Valores ausentes:

Data        0
Último      0
Abertura    0
Máxima      0
Mínima      0
Vol.        0
Var%        0
dtype: int64

## Etapa 6

In [6]:
# Duplicidade

print("Valores Duplicados:")
duplicated = dados_ibovespa.duplicated().sum()
print(duplicated)

datas_duplicadas = dados_ibovespa['Data'].duplicated().sum()
print(f"Quantidade de datas duplicadas: {datas_duplicadas}")

Valores Duplicados:
0
Quantidade de datas duplicadas: 0

## Etapa 7: Verificação de Inconsistências

### Regras de Negócio
- No mercado financeiro a `Máxima` de um dia nunca pode ser menor que a `Mínima` ou que a `Abertura` / `Último`.
- A `Mínima` nunca pode ser maior que qualquer outra cotação do dia.

### Coerência Temporal / Sequencial
- As datas estão ordenadas cronologicamente?
- Existem "saltos" anormais ou datas futuras?

### Formatos/Tipos
- Colunas numericas que contêm caracteres especias que impedem cálculos (como sufixo `M` em `Vol.`, vírgula `,` como separador decimal, `%` na variação)

In [7]:
inconsistencias_max_min = dados_ibovespa[dados_ibovespa['Máxima'] < dados_ibovespa['Mínima']]
inconsistencias_max_abertura = dados_ibovespa[dados_ibovespa['Máxima'] < dados_ibovespa['Abertura']]
inconsistencias_min_abertura = dados_ibovespa[dados_ibovespa['Mínima'] > dados_ibovespa['Abertura']]
inconsistencias_max_ultimo = dados_ibovespa[dados_ibovespa['Máxima'] < dados_ibovespa['Último']]
inconsistencias_min_ultimo = dados_ibovespa[dados_ibovespa['Mínima'] > dados_ibovespa['Último']]

print(f"Máxima menor que Mínima: {len(inconsistencias_max_min)}")
print(f"Máxima menor que Abertura: {len(inconsistencias_max_abertura)}")
print(f"Mínima maior que Abertura: {len(inconsistencias_min_abertura)}")
print(f"Máxima menor que Último: {len(inconsistencias_max_ultimo)}")
print(f"Mínima maior que Último: {len(inconsistencias_min_ultimo)}")

# Verificar se há valores negativos ou zerados onde não deveria
precos_negativos = dados_ibovespa[(dados_ibovespa[['Último', 'Abertura', 'Máxima', 'Mínima']] <= 0).any(axis=1)]
print(f"Linhas com preços <= 0: {len(precos_negativos)}")

Máxima menor que Mínima: 0
Máxima menor que Abertura: 0
Mínima maior que Abertura: 0
Máxima menor que Último: 0
Mínima maior que Último: 0
Linhas com preços <= 0: 0

### Conversão

In [ ]:
df_limpo = dados_ibovespa.copy()

df_limpo['Data'] = pd.to_datetime(df_limpo['Data'], format='%d.%m.%Y')

df_limpo['Var%'] = (
    df_limpo['Var%']
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

def converter_volume (valor):
    if pd.isna(valor) or valor == '-' or valor == "":
        return 0.0
    valor = str(valor).replace('.', '').replace(',', '.')
    if 'M' in valor:
        return float(valor.replace('M', '')) * 1e6
    elif 'B' in valor:
        return float(valor.replace('B', '')) * 1e9
    elif 'K' in valor:
        return float(valor.replace('K', '')) * 1e3
    else:
        return float(valor)

df_limpo['Vol.'] = df_limpo['Vol.'].apply(converter_volume)

df_limpo = df_limpo.sort_values(by='Data').reset_index(drop=True)

display(df_limpo.head(20))
df_limpo.info()

         Data  Último  Abertura  Máxima  Mínima        Vol.  Var%
0  2020-06-05  94.637    93.839  97.356  93.839  13320000.0  0.86
1  2020-06-08  97.645    94.640  97.693  94.635  11100000.0  3.18
2  2020-06-09  96.747    97.644  97.644  95.386  11290000.0 -0.92
3  2020-06-10  94.686    96.747  97.646  94.665  11740000.0 -2.13
4  2020-06-12  92.795    94.677  94.703  90.811  12790000.0 -2.00
5  2020-06-15  92.376    92.780  93.112  90.148  13320000.0 -0.45
6  2020-06-16  93.531    92.387  95.216  92.387  12030000.0  1.25
7  2020-06-17  95.547    93.531  96.611  93.531  11130000.0  2.16
8  2020-06-18  96.125    95.547  97.110  94.698  10010000.0  0.60
9  2020-06-19  96.572    96.138  97.540  95.874  13130000.0  0.47
10 2020-06-22  95.336    96.572  96.870  94.869   8260000.0 -1.28
11 2020-06-23  95.975    95.344  97.486  95.344   9750000.0  0.67
12 2020-06-24  94.377    95.974  95.974  93.259   9960000.0 -1.67
13 2020-06-25  95.983    94.382  96.260  94.152   8700000.0  1.70
14 2020-06-26  93.834    95.979  95.979  93.514   8440000.0 -2.24
15 2020-06-29  95.735    93.837  95.735  93.825   8910000.0  2.03
16 2020-06-30  95.056    95.728  96.257  94.806  10140000.0 -0.71
17 2020-07-01  96.203    95.062  96.852  95.062  10160000.0  1.21
18 2020-07-02  96.235    96.206  97.864  96.052  10060000.0  0.03
19 2020-07-03  96.765    96.237  96.765  95.803   5350000.0  0.55

<class 'pandas.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      995 non-null    datetime64[us]
 1   Último    995 non-null    float64
 2   Abertura  995 non-null    float64
 3   Máxima    995 non-null    float64
 4   Mínima    995 non-null    float64
 5   Vol.      995 non-null    float64
 6   Var%      995 non-null    float64
dtypes: datetime64[us](1), float64(6)
memory usage: 54.5 KB

### Padronização

In [9]:
# Padronizar nomes de colunas
df_limpo.columns = ['data', 'ultimo', 'abertura', 'maxima', 'minima', 'volume', 'var_pct']
# Padronizar índice
df_limpo = df_limpo.set_index('data').sort_index()

display(df_limpo.head(20))

            ultimo  abertura  maxima  minima      volume  var_pct
data
2020-06-05  94.637    93.839  97.356  93.839  13320000.0     0.86
2020-06-08  97.645    94.640  97.693  94.635  11100000.0     3.18
2020-06-09  96.747    97.644  97.644  95.386  11290000.0    -0.92
2020-06-10  94.686    96.747  97.646  94.665  11740000.0    -2.13
2020-06-12  92.795    94.677  94.703  90.811  12790000.0    -2.00
2020-06-15  92.376    92.780  93.112  90.148  13320000.0    -0.45
2020-06-16  93.531    92.387  95.216  92.387  12030000.0     1.25
2020-06-17  95.547    93.531  96.611  93.531  11130000.0     2.16
2020-06-18  96.125    95.547  97.110  94.698  10010000.0     0.60
2020-06-19  96.572    96.138  97.540  95.874  13130000.0     0.47
2020-06-22  95.336    96.572  96.870  94.869   8260000.0    -1.28
2020-06-23  95.975    95.344  97.486  95.344   9750000.0     0.67
2020-06-24  94.377    95.974  95.974  93.259   9960000.0    -1.67
2020-06-25  95.983    94.382  96.260  94.152   8700000.0     1.70
2020-06-26  93.834    95.979  95.979  93.514   8440000.0    -2.24
2020-06-29  95.735    93.837  95.735  93.825   8910000.0     2.03
2020-06-30  95.056    95.728  96.257  94.806  10140000.0    -0.71
2020-07-01  96.203    95.062  96.852  95.062  10160000.0     1.21
2020-07-02  96.235    96.206  97.864  96.052  10060000.0     0.03
2020-07-03  96.765    96.237  96.765  95.803   5350000.0     0.55